### ISSUE TITLE
example.js doesn't work

### ISSUE THREAD

**Issue by MatejMecka** [MatejMecka/HacktoberfestStats#2]
So that means the module doesn't work.

What happens is when you try to execute  it'll load a little and then be stuck and return nothing. And the Program won't quit.

Your Goal is to find the issue and submit a fix :D.

Happy Hacktoberfest.

**Comment by martin-fink** [comment]
I would like to take the issue if that's ok!

**Comment by MatejMecka** [comment]
@martin-fink Sure. Good luck and Have fun

**Comment by jataggart** [comment]
I've been digging into this and I think I know why it is happening: the page at `hacktoberfest.digitalocean.com/stats/${USERNAME}` is pretty dynamic and actually makes a request to the `github.com` API. Therefore, cheeriojs is unable to see any data since it technically is not part of the DOM at load time.

If you load up the [page](https://hacktoberfest.digitalocean.com/stats/MatejMecka) and view the network activity, you can see that a [request](https://api.github.com/search/issues?q=-label:invalid+created:2017-09-30T00:00:00-12:00..2017-10-31T23:59:59-12:00+type:pr+is:public+author:matejmecka&per_page=300) is made dynamically.

**Comment by martin-fink** [comment]
Was just about to comment that... This type of solution is not working for a dynamic site. It would be possible to do a simple request to the URL @jataggart posted and simply print the information in the returned json data.

**Comment by jespicas** [comment]
Hi,
I think exists 2 issues.
1 issue in example.js and other in main.js.

I made a little change and now, example return something.

Is my first change on any project in GitHub.
I don't know how proceed.
I clone a project, created new branch and try to push but give me a 403 .
Can you help me ?

**Comment by MatejMecka** [comment]
Did you try pushing on my project because you have to push it on yours.

**Comment by jespicas** [comment]
Now I created a fork and push in my fork.
How create a pull request  ?

**Comment by jespicas** [comment]
Done. pull request created. but without label ,and I don't know how assign reviewer, etc ...
I a newbie ::(
